name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Altere para a branch que você deseja que dispare o deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Especifique a versão do Python que você está usando

    - name: Install MkDocs and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs
        pip install mkdocs-material  # Adicione outros temas ou plugins aqui, se necessário

    - name: Build the site
      run: mkdocs build --site-dir site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
